language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
after_script:
- molecule --debug destroy
env:
  global:
  - secure: PZ/7daGZKo5YD7SbITkt4GkLm3H/0GaPnmA9cxytfgJ2nRKQaBh7Bvq14Y2XHHfrTn7LCOp8fNOpWnvs9w2AkrYr1nAAP+YMBSyPxNyw1aPlbYZkrSy9TagD00kJb4YqQmc2f5eBWIpxRpOS3bhh7tyAUvo/gGJZbhmGiMnj0HVq5PPaL+5gyCrLChGIiMBn8KYbKePBxEKduAj1Q7x6ObDtX68w7DajISu/VyjXLoZQg4I8hoxmga5Gjxo9FpMUmWMo31IQcBru6JUDJTapbMRcVjCpXybwYTdCHoHDIcyjFiKgxVy7I5pUPxNkXzgCFf9xP2A4M4QleT1MPymaSqbo1zKXRQYQDr/rFOte9q/RkoVdT65woKskCAblKxzwXxyAaW9t684aJpIq6va4noqoAvioSCVOsR5PHx0OF5BoPVdpAdxSEoAXwvmLbyuAxUuuJpclxfy9Xa78sFeX/jDkPJn1zFesaRP3XwE7Ay3UcfAsK8S2bmNJdAz016j8//5RU08LSoriwVVymg9eB0qAVi0De8z6CtjXs55KT0Nng9f/vAq4VJRVc6hisQw/l8NtzTzQPNo7sWcGE+ydcE++N0EY+EFIOclucn/4Dh5A5roBaU4m7hgwnQt0AC2J6JlyAQznOxb0GR2yC3dqL2klnTg/muvIM8yU0lbyCmI=
  - secure: liYy9IeIdt5+Ak8POhvYWUZCax1s60mjZ3SvJB+auwYjVGjoZlJmiG873jGbmSSRYHTfivSGtPza4bPU1+CaNDtcOeP/0G0yT4AGyPv0gjJSaLECa1s8cFFL8Qd8N1CIzBHdYWTpPB9XzM70RBXX61LFCUM1oSxWql9vJSPNzVuMNgafULqa0GxHxtKTGyVcNu6XwDzmijEOB8E5aK5GVnpzw0maO6ILOfy/hQhELcCwYShSmw+wtsuFMCCIbYTsYsWcor8aMOP+O0ywBcdSS22NKUPtwwLIyf8bWEytXzydL0r4dWBopJ5PrILbPqRmkcV44cLnIweUgJJrDl931t8HviUGqCA4vfkevbHgaWpte2FXRVmdPub7XoifSz5gBT/zw3Ie33lvvSxv0R3DVYQnAwhM0obTmNkvEoFHAT+UVHMMOP9aa6LeNVOTpikhu8lhzewnY7WovYNgmNkZznskyhlGbVecmnajv/xJIl/rixj+ANIn2nJlcfrrKC0PbdmgJqPcUMVqNDgnnSRgRrVw49L0Ea3+T26dgBDuh12v+GkkovDixuVf24soFLttGDvMkJz545dVtE0ISYzfgrYM6iWK68QSR+RaZ8P2czVlqWS4Bi7xRUwyr78ribQXiWvFmsRMCvHmw0Vm3B41+QbMCNm4lHw5ba1CM/HXgfw=
  - secure: BQIEbY4h46kwaG+2geVB1wZjjdYh8qowwzMSo3ZAHrtOmG8BFtuzAIMTug1Niv1Iy2JIjP2nw/LzdwP2327n81srAQgvIETAeF8+2kfhnTG0/cWsH0FzWxiQVgk3ObrBII/QMBZOKBz8mWRyuOh2b9ow4tijJIPj+FYEwA8iAsazSLOjH5f0eMUTgfGRDpZvsy4wOKvk7uHaA8HAip4FQzH6pXKe51UB1m13e+YXRi6WX2CSe96Zi7e9WrOgIanCq+BJLIpsrRY2l3GXt98z26vSgCAYR1e4lSykrHZgIliNTY0f9bj18cXka2I772HfIPCvHdIAerQAKaFcEw3fqtI1sZOAfzjGKhRKEjTN5Q2RA09LoJJaCDDOYscqOBDLGXhQjo7RMtFVhmDX0FguOUJORkUqujiAFW+1PfmGXCNFT0iq+2olSgCDkUFhQ+4TBJRgsFRT31gzqt87jTZIfRPOsblKdzmP1CWZo8TOsPJOdK26WeoO/xUuiLFMtyz1yPb4guLJQQVF3n4uUJj3BFteB2ivCswZ+nDIGrq8bdjZBGTNgThmyzakE9kEiYJdRRBrmUpafoCNUCos5SbjJB6frFmIf/0NuvVcUUdhgOA700l3di/p4Pajyigg8DydDFUYmVdyK443R4PIQB9XW3CdZwTonQ6fjugqGBFbKFA=
before_install:
- openssl aes-256-cbc -K $encrypted_fcd898bd2dd1_key -iv $encrypted_fcd898bd2dd1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine