---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
        state: present

    - name: Add MongoDB repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: yes
